// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7sCC_RhG9XDKWTsntkSGpcIPv0lcHvs',
    appId: '1:750656526163:web:107fed2cb980644b4d73a6',
    messagingSenderId: '750656526163',
    projectId: 'habittracker-283fd',
    authDomain: 'habittracker-283fd.firebaseapp.com',
    storageBucket: 'habittracker-283fd.firebasestorage.app',
    measurementId: 'G-VFZFKYD9QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9_19B_UNzXqA_HPIXi_trhqWChqWMXQ',
    appId: '1:750656526163:android:9c0e07341f5a49284d73a6',
    messagingSenderId: '750656526163',
    projectId: 'habittracker-283fd',
    storageBucket: 'habittracker-283fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gWiCvK7igJbPFK7NUanhcBOTMhtllDc',
    appId: '1:750656526163:ios:aa2312925d5eaa6f4d73a6',
    messagingSenderId: '750656526163',
    projectId: 'habittracker-283fd',
    storageBucket: 'habittracker-283fd.firebasestorage.app',
    iosBundleId: 'com.marinaskegro.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6gWiCvK7igJbPFK7NUanhcBOTMhtllDc',
    appId: '1:750656526163:ios:211d3da6626531924d73a6',
    messagingSenderId: '750656526163',
    projectId: 'habittracker-283fd',
    storageBucket: 'habittracker-283fd.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV7sCC_RhG9XDKWTsntkSGpcIPv0lcHvs',
    appId: '1:750656526163:web:107fed2cb980644b4d73a6',
    messagingSenderId: '750656526163',
    projectId: 'habittracker-283fd',
    authDomain: 'habittracker-283fd.firebaseapp.com',
    storageBucket: 'habittracker-283fd.firebasestorage.app',
    measurementId: 'G-VFZFKYD9QS',
  );
}